# Generated by Django 5.0.7 on 2024-07-25 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="pub_date",
        ),
    ]
