# Generated by Django 5.0.7 on 2024-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_item_author_todo_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="hidden",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
