# Generated by Django 4.2.18 on 2025-07-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_convert_hidden_to_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
